/** @file Raw event definitions — ambient log entries, hazards, and one-shot narrative events. */

export const MOUND_EVENTS = Object.freeze([
  { id: "screen-noise", text: "屏幕有雪花。", once: true, group: "hazard" },
  { id: "outside-knock", text: "舱外有敲击声。", once: true, group: "hazard" },
  { id: "drifter-arrive", text: "他在门口。呼吸沉重。", once: true, group: "story" },
  { id: "drifter-stay", text: "他留下了。他懂得如何密封墙缝。", once: true, group: "story" },
  { id: "pressure-rise", text: "舱内气压回升。", once: true, group: "story" },
  { id: "record-loaded", text: "记录载入。", once: true, group: "system" },
  { id: "electrolyzer-on", text: "制氧机嗡嗡作响。", once: true, group: "system" },
  { id: "ice-melt", text: "冰块在加热。白雾升腾。", once: true, group: "system" },
  { id: "array-ice", text: "阵列捕捉到了带冰的陨石。", once: true, group: "system" },
  { id: "air-fresh", text: "空气变清新了。", once: true, group: "system" },
  { id: "survivor-return", text: "又有人顺着信号摸索过来了。", once: false, group: "story" },
  { id: "scan-broadcast-fragment", text: "[雷达] 扫描到旧时代的广播碎片：\"...这里是星火号，我们需要补给...\"", once: false, group: "space" },
  { id: "scan-he3-cloud", text: "[雷达] 捕获到游离态高能气团，聚变堆反应强度瞬间飙升。", once: false, group: "space" },
  { id: "event-cryo-cache", text: "[发现] 发现漂浮的冷冻库，回收了一些古代密封剂（+50 密封剂）。", once: false, group: "space" },
  { id: "event-radiation-nebula", text: "[警告] 穿过高辐射星云，船体外壳微损，修复消耗 20 合金。", once: false, group: "space" },
  { id: "scan-anomaly-whisper", text: "[异常] 它在看着我们...在恒星的阴影里。", once: false, group: "space" },
  { id: "minor-voyage-static", text: "通讯频段捕捉到一段无意义的静电杂音。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-creak", text: "舱壁因温差产生轻微的金属扭曲声。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-clean", text: "自动除尘系统已完成外层装甲清理。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-gravity", text: "导航矩阵在远端探测到一次微弱的引力波动。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-life-support", text: "生命维持系统自检完成，循环率 99.8%。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-starlight", text: "观测窗外掠过一道冰冷的星光。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-reactor", text: "反应堆输出功率出现 0.02% 的正常波动。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-radiation", text: "检测到微量空间辐射，磁力盾已自动修正。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-filter", text: "主舱空气过滤器短暂升频，随后回落至静音档位。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-calibration", text: "航向标定仪刷新了一次恒星坐标缓存。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-particles", text: "远端被动阵列记录到一次短促粒子雨。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-trail", text: "推进尾迹在舷窗边缘留下细碎光纹。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-stress", text: "外层装甲应力条稳定在安全阈值以内。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-pressure", text: "低温阀组完成一次常规释压，舱内噪声轻微上扬。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-attitude", text: "姿态轮组完成微调，航线偏差被压回基线。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-longwave", text: "长波监听仅回收到背景宇宙噪声。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-thermal-loop", text: "热管理管路结束一次周期性冲刷。", once: false, group: "minor-voyage" },
  { id: "minor-voyage-shadow", text: "船体阴面反射到一簇迟滞的星光。", once: false, group: "minor-voyage" },
  { id: "milestone-10000", text: "[关键] 成功回收星火号先遣冷冻荚。载员上限已扩展至 8 人。", once: true, group: "story" },
  { id: "milestone-30000", text: "[环境] 信号背景变得异常纯净，地表的杂音彻底消失了。", once: true, group: "story" },
  { id: "milestone-60000", text: "[航向] 雷达捕捉到大型金属构件，这里曾是旧时代的轨道哨所。", once: true, group: "story" },
  { id: "milestone-100000", text: "[发现] 截获一段循环播放的加密坐标，指向更遥远的虚空。", once: true, group: "story" },
  { id: "hazard-crew-loss", text: "[紧急] 2号隔离舱外壳开裂！请确保有充足合金进行自动加固！", once: false, group: "hazard" },
  { id: "hazard-reactor-overload", text: "[警告] 冷却回路发生气锁，发电机组进入低功率保护模式！", once: false, group: "hazard" },
  { id: "hazard-auto-fault", text: "[警告] 逻辑总线受到带电粒子冲击，自动化流水线陷入混乱。", once: false, group: "hazard" },
  { id: "hazard-signal-jam", text: "[异常] 捕获到强力杂讯干扰，雷达系统完全瘫痪。", once: false, group: "hazard" },
  { id: "hazard-pressure-drop", text: "[紧急] 3号隔离舱发生泄漏，正在强制注压修复。", once: false, group: "hazard" }
]);
